[package]
name = "libflatview"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = "0.26"
thiserror = "1.0"
lazy_static = "1.4"
memmap2 = "0.6"
linked-hash-map = "0.5"
num-traits = "0.2"

[dev-dependencies]
tempfile = "3"
rand = "0.8"
rand_pcg = "0.3"
rand_distr = "0.4"
