name: macos_tests

on:
  - workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  ubuntu:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Cache rust stuff
      uses: Swatinem/rust-cache@v2

    - name: Run tests
      run: cargo test --all-features --release
