name: tests

on:
  - workflow_dispatch
  - pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  ubuntu-64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - i686-unknown-linux-gnu
          - i686-unknown-linux-musl
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
    steps:
    - uses: actions/checkout@v3

    - name: Install toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        target: ${{ matrix.target }}

    - name: Cache rust stuff
      uses: Swatinem/rust-cache@v2

    - name: Install multilib
      if: ${{ contains(matrix.target, 'i686-unknown-linux-') }}
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: gcc-multilib
        version: 1.0

    - name: Run tests
      run: cargo test --all-features --target ${{ matrix.target }} --release
