name: wine_tests

on:
  - workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: i686-pc-windows-gnu
            apt: wine32 gcc-mingw-w64-i686 libgcc-s1:i386 libstdc++6:i386
          - target: x86_64-pc-windows-gnu
            apt: wine64 gcc-mingw-w64-x86-64
    steps:
    - uses: actions/checkout@v3

    - name: Install toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        target: ${{ matrix.target }}

    - name: Cache rust stuff
      uses: Swatinem/rust-cache@v2

    - run: sudo apt-get remove liblldb-12 liblldb-13 mono-runtime
    - if: ${{ matrix.target == 'i686-pc-windows-gnu' }}
      run: sudo dpkg --add-architecture i386
    - if: ${{ matrix.target == 'i686-pc-windows-gnu' }}
      run: sudo apt-get update

    - name: Install APT dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: wine-binfmt wine ${{ matrix.apt }}
        version: 1.0

    - name: Run tests
      run: cargo test --all-features --target ${{ matrix.target }} --release
